// Auto-generated by swagger-to-apis.ts
// Run `npm run api` to regenerate from your Swagger endpoint

import { Http } from "../http";

export class SwaggerV3Api extends Http {
  // Add generated API methods here
}
